version: "3.8"
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEFAULT_PORT: 8080
    container_name: spring-webapp
    volumes:
      - ./build:/app/build
    ports:
      - '8080:8080'
    depends_on:
      - 'h2-db'
  h2-db:
    image: 'oscarfonts/h2'
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_USERNAME=sa
      - H2_PASSWORD=
    ports:
      - '81:81'

volumes:
  h2-data:
