version: "3.8"
services:
  board:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEFAULT_PORT: 8080
    container_name: board-server
    volumes:
      - ./build:/app/build
    ports:
      - '8080:8080'
    depends_on:
      - 'mysql'
  mysql:
    image: 'mysql:8.0'
    env_file:
      - ./env/mysql.env