version: "3.8"
services:
  board:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEFAULT_PORT: 8080
    container_name: board-server
    volumes:
      - ./build:/app/build
    ports:
      - '8080:8080'
    depends_on:
      - 'mysql'
      - 'redis'
  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    restart: always
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    env_file:
      - ./env/mysql.env
    volumes:
      - './data/db/initdb.d:/docker-entrypoint-initdb.d'
      - './data/db/mysql:/var/lib/mysql'
  redis:
    image: redis:7.2.4
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'