management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
  server:
    port: 8080
#      show-details: always

info:
  app:
    name: spring-webapp
    company: du

spring:
  messages:
    basename: messages, errors
  main:
    allow-bean-definition-overriding: true # SpringBoot 2.1 부터 Bean Overriding Default값이 비활성화 되어 있어 활성화 처리 필요
  jpa:
    hibernate:
      ddl-auto: validate # JPA Auto DDL 설정 -> 개발 초기 참고용으로 사용
    properties:
      hibernate:
        format_sql: true
  # DB Info
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # Redis
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_IP}
      port: ${REDIS_PORT}
      password:
      repositories:
        enabled: false

expire:
  defaultTime: 3600

# JPA Log
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE